### ISSUE TITLE
Open graph image in chat and text Input

### ISSUE THREAD

**Issue by vebiolavanessa** [kontenbase/kontenbase#13] opened 2021-12-18 04:40 UTC
First Issue :  
Current Behavior : Open graph URL still doesn't work yet

Expected Behavior : Should it work

Second Issue :
Current Behavior : The cursor goes forward to the first text when it's out of the text input chat.

Expected Behavior : Chat should stay focus the last text when user add text or comes out to text input

Video : 
https://share.vidyard.com/watch/kqy4qRcdVEF7vyYge6oSvK

![image](https://user-images.githubusercontent.com/90052030/146629192-b83a5b33-110a-4dfd-b7ed-a2eaf97fb026.png)

**Comment by mhaidarhanif** [comment] 2021-12-18 14:41
@vebiolavanessa This is actually not a bug since it's not part of the basic features.

The automatic OpenGraph preview in this basic app is too complex.

Confirm with @aswara to close this issue as this is not a bug, but it should be out of scope.

**Closed by mhaidarhanif** 2021-12-18 14:41 UTC
Labels: bug, enhancement
