### ISSUE TITLE
Chat time is not updated in real time

### ISSUE THREAD

**Issue by vebiolavanessa** [kontenbase/kontenbase#12] opened 2021-12-18 03:12 UTC
Current Behavior : Chat time still doesn't real time yet. Overall chatting can be used but the chat time doesn't change directly except if we add new chat then the time will change. 

Expected Behavior : the chat time should be changed automatically (real time)

Reported By Vebiola Vanessa

![image](https://user-images.githubusercontent.com/90052030/146627069-53a52a52-f7c3-4c88-a5e5-ad0f04082b87.png)

**Comment by mhaidarhanif** [comment] 2021-12-18 14:41
@vebiolavanessa This is actually not a bug since it's not part of the basic features.

The chat timestamp is fine not to be in true real time for this example.

Confirm with @aswara to close this issue as this is not a bug, but it should be out of scope.

**Closed by mhaidarhanif** 2021-12-18 14:41 UTC
Labels: bug, enhancement
